spring.application.name=dinner-roulette


spring.datasource.url=jdbc:postgresql://localhost:5432/DinnerRoulette
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create

# Useful for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB













































